version: '2'

services:
  caronae-backend:
    container_name: caronae-backend
    image: caronae/backend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file: config.env
    volumes:
      - .:/var/www

  caronae-backend-worker:
    container_name: caronae-backend-worker
    image: caronae/backend
    command: queue
    volumes_from:
      - caronae-backend
    env_file: config.env

  nginx:
    container_name: nginx
    image: caronae/nginx
    volumes_from:
      - caronae-backend
    ports:
      - 8000:8000

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=caronae
      - POSTGRES_DB=caronae
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
